// Code generated by ent, DO NOT EDIT.

package attemptanswer

import (
	"encore.app/ent/predicate"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.AttemptAnswer {
	return predicate.AttemptAnswer(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.AttemptAnswer {
	return predicate.AttemptAnswer(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.AttemptAnswer {
	return predicate.AttemptAnswer(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.AttemptAnswer {
	return predicate.AttemptAnswer(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.AttemptAnswer {
	return predicate.AttemptAnswer(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.AttemptAnswer {
	return predicate.AttemptAnswer(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.AttemptAnswer {
	return predicate.AttemptAnswer(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.AttemptAnswer {
	return predicate.AttemptAnswer(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.AttemptAnswer {
	return predicate.AttemptAnswer(sql.FieldLTE(FieldID, id))
}

// AttemptID applies equality check predicate on the "attempt_id" field. It's identical to AttemptIDEQ.
func AttemptID(v uuid.UUID) predicate.AttemptAnswer {
	return predicate.AttemptAnswer(sql.FieldEQ(FieldAttemptID, v))
}

// QuestionID applies equality check predicate on the "question_id" field. It's identical to QuestionIDEQ.
func QuestionID(v uuid.UUID) predicate.AttemptAnswer {
	return predicate.AttemptAnswer(sql.FieldEQ(FieldQuestionID, v))
}

// UserText applies equality check predicate on the "user_text" field. It's identical to UserTextEQ.
func UserText(v string) predicate.AttemptAnswer {
	return predicate.AttemptAnswer(sql.FieldEQ(FieldUserText, v))
}

// AnswerID applies equality check predicate on the "answer_id" field. It's identical to AnswerIDEQ.
func AnswerID(v uuid.UUID) predicate.AttemptAnswer {
	return predicate.AttemptAnswer(sql.FieldEQ(FieldAnswerID, v))
}

// AttemptIDEQ applies the EQ predicate on the "attempt_id" field.
func AttemptIDEQ(v uuid.UUID) predicate.AttemptAnswer {
	return predicate.AttemptAnswer(sql.FieldEQ(FieldAttemptID, v))
}

// AttemptIDNEQ applies the NEQ predicate on the "attempt_id" field.
func AttemptIDNEQ(v uuid.UUID) predicate.AttemptAnswer {
	return predicate.AttemptAnswer(sql.FieldNEQ(FieldAttemptID, v))
}

// AttemptIDIn applies the In predicate on the "attempt_id" field.
func AttemptIDIn(vs ...uuid.UUID) predicate.AttemptAnswer {
	return predicate.AttemptAnswer(sql.FieldIn(FieldAttemptID, vs...))
}

// AttemptIDNotIn applies the NotIn predicate on the "attempt_id" field.
func AttemptIDNotIn(vs ...uuid.UUID) predicate.AttemptAnswer {
	return predicate.AttemptAnswer(sql.FieldNotIn(FieldAttemptID, vs...))
}

// QuestionIDEQ applies the EQ predicate on the "question_id" field.
func QuestionIDEQ(v uuid.UUID) predicate.AttemptAnswer {
	return predicate.AttemptAnswer(sql.FieldEQ(FieldQuestionID, v))
}

// QuestionIDNEQ applies the NEQ predicate on the "question_id" field.
func QuestionIDNEQ(v uuid.UUID) predicate.AttemptAnswer {
	return predicate.AttemptAnswer(sql.FieldNEQ(FieldQuestionID, v))
}

// QuestionIDIn applies the In predicate on the "question_id" field.
func QuestionIDIn(vs ...uuid.UUID) predicate.AttemptAnswer {
	return predicate.AttemptAnswer(sql.FieldIn(FieldQuestionID, vs...))
}

// QuestionIDNotIn applies the NotIn predicate on the "question_id" field.
func QuestionIDNotIn(vs ...uuid.UUID) predicate.AttemptAnswer {
	return predicate.AttemptAnswer(sql.FieldNotIn(FieldQuestionID, vs...))
}

// UserTextEQ applies the EQ predicate on the "user_text" field.
func UserTextEQ(v string) predicate.AttemptAnswer {
	return predicate.AttemptAnswer(sql.FieldEQ(FieldUserText, v))
}

// UserTextNEQ applies the NEQ predicate on the "user_text" field.
func UserTextNEQ(v string) predicate.AttemptAnswer {
	return predicate.AttemptAnswer(sql.FieldNEQ(FieldUserText, v))
}

// UserTextIn applies the In predicate on the "user_text" field.
func UserTextIn(vs ...string) predicate.AttemptAnswer {
	return predicate.AttemptAnswer(sql.FieldIn(FieldUserText, vs...))
}

// UserTextNotIn applies the NotIn predicate on the "user_text" field.
func UserTextNotIn(vs ...string) predicate.AttemptAnswer {
	return predicate.AttemptAnswer(sql.FieldNotIn(FieldUserText, vs...))
}

// UserTextGT applies the GT predicate on the "user_text" field.
func UserTextGT(v string) predicate.AttemptAnswer {
	return predicate.AttemptAnswer(sql.FieldGT(FieldUserText, v))
}

// UserTextGTE applies the GTE predicate on the "user_text" field.
func UserTextGTE(v string) predicate.AttemptAnswer {
	return predicate.AttemptAnswer(sql.FieldGTE(FieldUserText, v))
}

// UserTextLT applies the LT predicate on the "user_text" field.
func UserTextLT(v string) predicate.AttemptAnswer {
	return predicate.AttemptAnswer(sql.FieldLT(FieldUserText, v))
}

// UserTextLTE applies the LTE predicate on the "user_text" field.
func UserTextLTE(v string) predicate.AttemptAnswer {
	return predicate.AttemptAnswer(sql.FieldLTE(FieldUserText, v))
}

// UserTextContains applies the Contains predicate on the "user_text" field.
func UserTextContains(v string) predicate.AttemptAnswer {
	return predicate.AttemptAnswer(sql.FieldContains(FieldUserText, v))
}

// UserTextHasPrefix applies the HasPrefix predicate on the "user_text" field.
func UserTextHasPrefix(v string) predicate.AttemptAnswer {
	return predicate.AttemptAnswer(sql.FieldHasPrefix(FieldUserText, v))
}

// UserTextHasSuffix applies the HasSuffix predicate on the "user_text" field.
func UserTextHasSuffix(v string) predicate.AttemptAnswer {
	return predicate.AttemptAnswer(sql.FieldHasSuffix(FieldUserText, v))
}

// UserTextIsNil applies the IsNil predicate on the "user_text" field.
func UserTextIsNil() predicate.AttemptAnswer {
	return predicate.AttemptAnswer(sql.FieldIsNull(FieldUserText))
}

// UserTextNotNil applies the NotNil predicate on the "user_text" field.
func UserTextNotNil() predicate.AttemptAnswer {
	return predicate.AttemptAnswer(sql.FieldNotNull(FieldUserText))
}

// UserTextEqualFold applies the EqualFold predicate on the "user_text" field.
func UserTextEqualFold(v string) predicate.AttemptAnswer {
	return predicate.AttemptAnswer(sql.FieldEqualFold(FieldUserText, v))
}

// UserTextContainsFold applies the ContainsFold predicate on the "user_text" field.
func UserTextContainsFold(v string) predicate.AttemptAnswer {
	return predicate.AttemptAnswer(sql.FieldContainsFold(FieldUserText, v))
}

// AnswerIDEQ applies the EQ predicate on the "answer_id" field.
func AnswerIDEQ(v uuid.UUID) predicate.AttemptAnswer {
	return predicate.AttemptAnswer(sql.FieldEQ(FieldAnswerID, v))
}

// AnswerIDNEQ applies the NEQ predicate on the "answer_id" field.
func AnswerIDNEQ(v uuid.UUID) predicate.AttemptAnswer {
	return predicate.AttemptAnswer(sql.FieldNEQ(FieldAnswerID, v))
}

// AnswerIDIn applies the In predicate on the "answer_id" field.
func AnswerIDIn(vs ...uuid.UUID) predicate.AttemptAnswer {
	return predicate.AttemptAnswer(sql.FieldIn(FieldAnswerID, vs...))
}

// AnswerIDNotIn applies the NotIn predicate on the "answer_id" field.
func AnswerIDNotIn(vs ...uuid.UUID) predicate.AttemptAnswer {
	return predicate.AttemptAnswer(sql.FieldNotIn(FieldAnswerID, vs...))
}

// AnswerIDIsNil applies the IsNil predicate on the "answer_id" field.
func AnswerIDIsNil() predicate.AttemptAnswer {
	return predicate.AttemptAnswer(sql.FieldIsNull(FieldAnswerID))
}

// AnswerIDNotNil applies the NotNil predicate on the "answer_id" field.
func AnswerIDNotNil() predicate.AttemptAnswer {
	return predicate.AttemptAnswer(sql.FieldNotNull(FieldAnswerID))
}

// HasAttempt applies the HasEdge predicate on the "attempt" edge.
func HasAttempt() predicate.AttemptAnswer {
	return predicate.AttemptAnswer(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, AttemptTable, AttemptColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAttemptWith applies the HasEdge predicate on the "attempt" edge with a given conditions (other predicates).
func HasAttemptWith(preds ...predicate.Attempt) predicate.AttemptAnswer {
	return predicate.AttemptAnswer(func(s *sql.Selector) {
		step := newAttemptStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasQuestion applies the HasEdge predicate on the "question" edge.
func HasQuestion() predicate.AttemptAnswer {
	return predicate.AttemptAnswer(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, QuestionTable, QuestionColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasQuestionWith applies the HasEdge predicate on the "question" edge with a given conditions (other predicates).
func HasQuestionWith(preds ...predicate.Question) predicate.AttemptAnswer {
	return predicate.AttemptAnswer(func(s *sql.Selector) {
		step := newQuestionStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAnswer applies the HasEdge predicate on the "answer" edge.
func HasAnswer() predicate.AttemptAnswer {
	return predicate.AttemptAnswer(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, AnswerTable, AnswerColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAnswerWith applies the HasEdge predicate on the "answer" edge with a given conditions (other predicates).
func HasAnswerWith(preds ...predicate.Answer) predicate.AttemptAnswer {
	return predicate.AttemptAnswer(func(s *sql.Selector) {
		step := newAnswerStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AttemptAnswer) predicate.AttemptAnswer {
	return predicate.AttemptAnswer(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AttemptAnswer) predicate.AttemptAnswer {
	return predicate.AttemptAnswer(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AttemptAnswer) predicate.AttemptAnswer {
	return predicate.AttemptAnswer(sql.NotPredicates(p))
}
