// Code generated by encore. DO NOT EDIT.
// Based on quiz-app-43t2 backend API

export type BaseURL = string;
export const Local: BaseURL = "http://127.0.0.1:4000";
export const Environment = (name: string): BaseURL =>
  `https://${name}-quiz-app-43t2.encr.app`;

// ===== TYPES =====

export interface RegisterRequest {
  email: string;
  password: string;
  role: string;
}

export interface LoginRequest {
  email: string;
  password: string;
}

export interface AuthResponse {
  token: string;
  role: string;
}

export interface Answer {
  id: string;
  text: string;
  is_correct: boolean;
  order_index: number;
}

export interface Question {
  id: string;
  text: string;
  order_index: number;
  question_type: string;
  answers: Answer[];
}

export interface Quiz {
  id: string;
  title: string;
  is_published: boolean;
  pass_threshold: number;
  one_attempt: boolean;
  show_answers: boolean;
  created_by: string;
  questions?: Question[];
}

export interface QuizListItem {
  id: string;
  title: string;
  is_published: boolean;
  question_count: number;
  pass_threshold: number;
  one_attempt: boolean;
  show_answers: boolean;
  status: string;
  score: number;
  percent: number;
  passed: boolean;
}

export interface CreateAnswer {
  text: string;
  is_correct: boolean;
  order_index: number;
}

export interface CreateQuestion {
  text: string;
  order_index: number;
  question_type: string;
  answers: CreateAnswer[];
}

export interface CreateQuizRequest {
  title: string;
  is_published: boolean;
  pass_threshold: number;
  one_attempt: boolean;
  show_answers: boolean;
  questions: CreateQuestion[];
}

export interface PublishRequest {
  is_published: boolean;
}

export interface MatchPair {
  left_answer_id: string;
  right_answer_id: string;
}

export interface SubmitAnswer {
  question_id: string;
  answer_id: string;
  text_answer?: string;
  match_pairs?: MatchPair[];
}

export interface SubmitRequest {
  answers: SubmitAnswer[];
}

export interface AnswerDetail {
  question_text: string;
  your_answer: string;
  correct_answer: string;
  is_correct: boolean;
}

export interface SubmitResult {
  score: number;
  total: number;
  percent: number;
  passed: boolean;
  show_answers: boolean;
  details?: AnswerDetail[];
}

export interface QuizListResponse {
  quizzes: QuizListItem[];
}

export interface QuizResponse {
  quiz: Quiz;
}

export interface MessageResponse {
  message: string;
}

// ===== CLIENT =====

export class APIError extends Error {
  code: string;
  constructor(message: string, code: string) {
    super(message);
    this.code = code;
  }
}

export function isAPIError(err: unknown): err is APIError {
  return err instanceof APIError;
}

export default class Client {
  private baseURL: string;
  private authToken?: () => string | null;

  auth: AuthService;
  quiz: QuizService;

  constructor(baseURL: BaseURL, options?: { auth?: () => string | null }) {
    this.baseURL = baseURL.replace(/\/$/, "");
    this.authToken = options?.auth;
    this.auth = new AuthService(this);
    this.quiz = new QuizService(this);
  }

  async request<T>(
    method: string,
    path: string,
    body?: unknown
  ): Promise<T> {
    const headers: Record<string, string> = {
      "Content-Type": "application/json",
    };

    const token = this.authToken?.();
    if (token) {
      headers["Authorization"] = `Bearer ${token}`;
    }

    const res = await fetch(`${this.baseURL}${path}`, {
      method,
      headers,
      body: body !== undefined ? JSON.stringify(body) : undefined,
    });

    if (!res.ok) {
      let message = res.statusText;
      try {
        const data = await res.json();
        message = data.message || data.error || message;
      } catch {}
      throw new APIError(message, String(res.status));
    }

    return res.json() as Promise<T>;
  }
}

class AuthService {
  constructor(private client: Client) {}

  Register(req: RegisterRequest): Promise<AuthResponse> {
    return this.client.request("POST", "/auth/register", req);
  }

  Login(req: LoginRequest): Promise<AuthResponse> {
    return this.client.request("POST", "/auth/login", req);
  }
}

class QuizService {
  constructor(private client: Client) {}

  // ADMIN
  AdminListQuizzes(): Promise<QuizListResponse> {
    return this.client.request("GET", "/admin/quizzes");
  }

  AdminCreateQuiz(req: CreateQuizRequest): Promise<QuizResponse> {
    return this.client.request("POST", "/admin/quizzes", req);
  }

  AdminGetQuiz(id: string): Promise<QuizResponse> {
    return this.client.request("GET", `/admin/quizzes/${id}`);
  }

  AdminUpdateQuiz(id: string, req: CreateQuizRequest): Promise<QuizResponse> {
    return this.client.request("PUT", `/admin/quizzes/${id}`, req);
  }

  AdminDeleteQuiz(id: string): Promise<MessageResponse> {
    return this.client.request("DELETE", `/admin/quizzes/${id}`);
  }

  AdminPublishQuiz(id: string, req: PublishRequest): Promise<MessageResponse> {
    return this.client.request("PATCH", `/admin/quizzes/${id}/publish`, req);
  }

  // USER
  ListQuizzes(): Promise<QuizListResponse> {
    return this.client.request("GET", "/quizzes");
  }

  GetQuiz(id: string): Promise<QuizResponse> {
    return this.client.request("GET", `/quizzes/${id}`);
  }

  GetQuizResult(id: string): Promise<SubmitResult> {
    return this.client.request("GET", `/quizzes/${id}/result`);
  }

  SubmitQuiz(id: string, req: SubmitRequest): Promise<SubmitResult> {
    return this.client.request("POST", `/quizzes/${id}/submit`, req);
  }
}
